export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SELECT_INDUSTRY = 'SELECT_INDUSTRY';

export const GET_INDUSTRIES = 'GET_INDUSTRIES';
export const GET_INDUSTRIES_SUCCESS = 'GET_INDUSTRIES_SUCCESS';

export const ADMIN_GET_INDUSTRIES_LIST = 'ADMIN_GET_INDUSTRIES_LIST';
export const ADMIN_GET_INDUSTRIES_LIST_SUCCESS =
  'ADMIN_GET_INDUSTRIES_LIST_SUCCESS';
export const ADMIN_GET_INDUSTRIES_LIST_FAILURE =
  'ADMIN_GET_INDUSTRIES_LIST_FAILURE';

export const CREATE_INDUSTRY = 'CREATE_INDUSTRY';
export const CREATE_INDUSTRY_SUCCESS = 'CREATE_INDUSTRY_SUCCESS';
export const CREATE_INDUSTRY_FAILURE = 'CREATE_INDUSTRY_FAILURE';

export const UPDATE_INDUSTRY = 'UPDATE_INDUSTRY';
export const UPDATE_INDUSTRY_SUCCESS = 'UPDATE_INDUSTRY_SUCCESS';
export const UPDATE_INDUSTRY_FAILURE = 'UPDATE_INDUSTRY_FAILURE';

export const DELETE_INDUSTRY = 'DELETE_INDUSTRY';
export const DELETE_INDUSTRY_SUCCESS = 'DELETE_INDUSTRY_SUCCESS';
export const DELETE_INDUSTRY_FAILURE = 'DELETE_INDUSTRY_FAILURE';
