export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

export const EMPLOYER_GET_JOBS = 'EMPLOYER_GET_JOBS';
export const EMPLOYER_GET_JOBS_SUCCESS = 'EMPLOYER_GET_JOBS_SUCCESS';
export const EMPLOYER_GET_JOBS_FAILURE = 'EMPLOYER_GET_JOBS_FAILURE';
