export const CREATE_JOB = 'CREATE_JOB';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';

export const UPDATE_JOB = 'UPDATE_JOB';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCESS';
export const UPDATE_JOB_FAILURE = 'UPDATE_JOB_FAILURE';

export const GET_JOB = 'GET_JOB';
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const GET_JOB_FAILURE = 'GET_JOB_FAILURE';

export const EMPLOYER_GET_JOBS = 'EMPLOYER_GET_JOBS';
export const EMPLOYER_GET_JOBS_SUCCESS = 'EMPLOYER_GET_JOBS_SUCCESS';
export const EMPLOYER_GET_JOBS_FAILURE = 'EMPLOYER_GET_JOBS_FAILURE';

export const APPLY_JOB = 'APPLY_JOB';
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_FAILURE = 'APPLY_JOB_FAILURE';

export const SEARCH_JOB = 'SEARCH_JOB';
export const SEARCH_JOB_SUCCESS = 'SEARCH_JOB_SUCCESS';
export const SEARCH_JOB_FAILURE = 'SEARCH_JOB_FAILURE';

export const EMPLOYER_DELETE_JOB = 'EMPLOYER_DELETE_JOB';
export const EMPLOYER_DELETE_JOB_SUCCESS = 'EMPLOYER_DELETE_JOB_SUCCESS';
export const EMPLOYER_DELETE_JOB_FAILURE = 'EMPLOYER_DELETE_JOB_FAILURE';

export const GET_JOBS_APPLIED = 'GET_JOBS_APPLIED';
export const GET_JOBS_APPLIED_SUCCESS = 'GET_JOBS_APPLIED_SUCCESS';
export const GET_JOBS_APPLIED_FAILURE = 'GET_JOBS_APPLIED_FAILURE';
