export const GET_DASHBOARD_ADMIN = 'GET_DASHBOARD_ADMIN';
export const GET_DASHBOARD_ADMIN_SUCCESS = 'GET_DASHBOARD_ADMIN_SUCCESS';
export const GET_DASHBOARD_ADMIN_FAILURE = 'GET_DASHBOARD_ADMIN_FAILURE';
