export const GET_DASHBOARD_ADMIN = 'GET_DASHBOARD_ADMIN';
export const GET_DASHBOARD_ADMIN_SUCCESS = 'GET_DASHBOARD_ADMIN_SUCCESS';
export const GET_DASHBOARD_ADMIN_FAILURE = 'GET_DASHBOARD_ADMIN_FAILURE';

export const GET_DASHBOARD_EMPLOYER = 'GET_DASHBOARD_EMPLOYER';
export const GET_DASHBOARD_EMPLOYER_SUCCESS = 'GET_DASHBOARD_EMPLOYER_SUCCESS';
export const GET_DASHBOARD_EMPLOYER_FAILURE = 'GET_DASHBOARD_EMPLOYER_FAILURE';
