export const REGISTER_EMPLOYER = 'REGISTER_EMPLOYER';
export const REGISTER_EMPLOYER_SUCCESS = 'REGISTER_EMPLOYER_SUCCESS';
export const REGISTER_EMPLOYER_FAILURE = 'REGISTER_EMPLOYER_FAILURE';

export const LOGIN_EMPLOYER = 'LOGIN_EMPLOYER';
export const LOGIN_EMPLOYER_SUCCESS = 'LOGIN_EMPLOYER_SUCCESS';
export const LOGIN_EMPLOYER_FAILURE = 'LOGIN_EMPLOYER_FAILURE';
