export const REGISTER_JOBSEEKER = 'REGISTER_JOBSEEKER';
export const REGISTER_JOBSEEKER_SUCCESS = 'REGISTER_JOBSEEKER_SUCCESS';
export const REGISTER_JOBSEEKER_FAILURE = 'REGISTER_JOBSEEKER_FAILURE';

export const LOGIN_JOBSEEKER = 'JOBSEEKER_LOGIN';
export const LOGIN_JOBSEEKER_SUCCESS = 'JOBSEEKER_LOGIN_SUCCESS';
export const LOGIN_JOBSEEKER_FAILURE = 'JOBSEEKER_LOGIN_FAILURE';

export const GET_CURRENT_JOBSEEKER = 'GET_CURRENT_JOBSEEKER';
export const GET_CURRENT_JOBSEEKER_SUCCESS = 'GET_CURRENT_JOBSEEKER_SUCCESS';
export const GET_CURRENT_JOBSEEKER_FAILURE = 'GET_CURRENT_JOBSEEKER_FAILURE';

export const REGISTER_EMPLOYER = 'REGISTER_EMPLOYER';
export const REGISTER_EMPLOYER_SUCCESS = 'REGISTER_EMPLOYER_SUCCESS';
export const REGISTER_EMPLOYER_FAILURE = 'REGISTER_EMPLOYER_FAILURE';

export const GET_INFO_EMPLOYER = 'GET_INFO_EMPLOYER';
export const GET_INFO_EMPLOYER_SUCCESS = 'GET_INFO_USER_SUCCESS';

export const LOGOUT_EMPLOYER = 'LOGOUT_EMPLOYER';

export const LOGIN_EMPLOYER = 'LOGIN_EMPLOYER';
export const LOGIN_EMPLOYER_SUCCESS = 'LOGIN_EMPLOYER_SUCCESS';
export const LOGIN_EMPLOYER_FAILURE = 'LOGIN_EMPLOYER_FAILURE';

export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_FAILURE = 'LOGIN_ADMIN_FAILURE';

export const GET_INFO_ADMIN = 'GET_INFO_ADMIN';
export const GET_INFO_ADMIN_SUCCESS = 'GET_INFO_ADMIN_SUCCESS';
export const GET_INFO_ADMIN_FAILURE = 'GET_INFO_ADMIN_FAILURE';

export const LOGOUT = 'LOGOUT';
