export const SAVE_JOB = 'SAVE_JOB';
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCESS';
export const SAVE_JOB_FAILURE = 'SAVE_JOB_FAILURE_FAILURE';

export const GET_JOBS_SAVED = 'GET_JOBS_SAVED';
export const GET_JOBS_SAVED_SUCCESS = 'GET_JOBS_SAVED_SUCCESS';
export const GET_JOBS_SAVED_FAILURE = 'GET_JOBS_SAVED_FAILURE';

export const DELETE_JOBS_SAVED = 'DELETE_JOBS_SAVED';
export const DELETE_JOBS_SAVED_SUCCESS = 'DELETE_JOBS_SAVED_SUCCESS';
export const DELETE_JOBS_SAVED_FAILURE = 'DELETE_JOBS_SAVED_FAILURE';
