export const OPEN_MODAL = 'OPEN_MODAL';

export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CREATE_OFFICE = 'CREATE_OFFICE';
export const CREATE_OFFICE_SUCCESS = 'CREATE_OFFICE_SUCCESS';

export const GET_OFFICES = 'GET_OFFICES';
export const GET_OFFICES_SUCCESS = 'GET_OFFICES_SUCCESS';

export const GET_OFFICE = 'GET_OFFICE';
export const GET_OFFICE_SUCCESS = 'GET_OFFICE_SUCCESS';

export const UPDATE_OFFICE = 'UPDATE_OFFICE';
export const UPDATE_OFFICE_SUCCESS = 'UPDATE_OFFICE_SUCCESS';

export const DELETE_OFFICE = 'DELETE_OFFICE';
export const DELETE_OFFICE_SUCCESS = 'DELETE_OFFICE_SUCCESS';
