export const ADMIN_GET_COMPANIES_LIST = 'ADMIN_GET_COMPANIES_LIST';
export const ADMIN_GET_COMPANIES_LIST_SUCCESS =
  'ADMIN_GET_COMPANIES_LIST_SUCCESS';

export const EMPLOYER_UPDATE_COMPANY = 'EMPLOYER_UPDATE_COMPANY';
export const EMPLOYER_UPDATE_COMPANY_SUCCESS =
  'EMPLOYER_UPDATE_COMPANY_SUCCESS';
export const EMPLOYER_UPDATE_COMPANY_FAILURE =
  'EMPLOYER_UPDATE_COMPANY_FAILURE';
