export const ADMIN_GET_COMPANIES_LIST = 'ADMIN_GET_COMPANIES_LIST';
export const ADMIN_GET_COMPANIES_LIST_SUCCESS =
  'ADMIN_GET_COMPANIES_LIST_SUCCESS';

export const EMPLOYER_UPDATE_COMPANY = 'EMPLOYER_UPDATE_COMPANY';
export const EMPLOYER_UPDATE_COMPANY_SUCCESS =
  'EMPLOYER_UPDATE_COMPANY_SUCCESS';
export const EMPLOYER_UPDATE_COMPANY_FAILURE =
  'EMPLOYER_UPDATE_COMPANY_FAILURE';

export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const ADMIN_GET_COMPANIES_PENDING = 'ADMIN_GET_COMPANIES_PENDING';
export const ADMIN_GET_COMPANIES_PENDING_SUCCESS =
  'ADMIN_GET_COMPANIES_PENDING_SUCCESS';
