export const ADMIN_GET_COMPANIES_LIST = 'ADMIN_GET_COMPANIES_LIST';
export const ADMIN_GET_COMPANIES_LIST_SUCCESS =
  'ADMIN_GET_COMPANIES_LIST_SUCCESS';

export const EMPLOYER_UPDATE_COMPANY = 'EMPLOYER_UPDATE_COMPANY';
export const EMPLOYER_UPDATE_COMPANY_SUCCESS =
  'EMPLOYER_UPDATE_COMPANY_SUCCESS';
export const EMPLOYER_UPDATE_COMPANY_FAILURE =
  'EMPLOYER_UPDATE_COMPANY_FAILURE';

export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const ADMIN_GET_COMPANIES_PENDING = 'ADMIN_GET_COMPANIES_PENDING';
export const ADMIN_GET_COMPANIES_PENDING_SUCCESS =
  'ADMIN_GET_COMPANIES_PENDING_SUCCESS';
export const ADMIN_GET_COMPANIES_PENDING_FAILURE =
  'ADMIN_GET_COMPANIES_PENDING_FAILURE';

export const ADMIN_GET_COMPANIES_ACTIVE = 'ADMIN_GET_COMPANIES_ACTIVE';
export const ADMIN_GET_COMPANIES_ACTIVE_SUCCESS =
  'ADMIN_GET_COMPANIES_ACTIVE_SUCCESS';
export const ADMIN_GET_COMPANIES_ACTIVE_FAILURE =
  'ADMIN_GET_COMPANIES_ACTIVE_FAILURE';

export const ADMIN_GET_COMPANIES_REJECTED = 'ADMIN_GET_COMPANIES_REJECTED';
export const ADMIN_GET_COMPANIES_REJECTED_SUCCESS =
  'ADMIN_GET_COMPANIES_REJECTED_SUCCESS';
export const ADMIN_GET_COMPANIES_REJECTED_FAILURE =
  'ADMIN_GET_COMPANIES_REJECTED_FAILURE';

export const ADMIN_UPDATE_COMPANY_STATUS = 'ADMIN_UPDATE_COMPANY_STATUS';
export const ADMIN_UPDATE_COMPANY_STATUS_SUCCESS =
  'ADMIN_UPDATE_COMPANY_STATUS_SUCCESS';

export const FOLLOW_COMPANY = 'FOLLOW_COMPANY';
export const FOLLOW_COMPANY_SUCCESS = 'FOLLOW_COMPANY_SUCCESS';

export const GET_FOLLOWING_COMPANIES = 'GET_FOLLOWING_COMPANIES';
export const GET_FOLLOWING_COMPANIES_SUCCESS =
  'GET_FOLLOWING_COMPANIES_SUCCESS';

export const UN_FOLLOW_COMPANY = 'UN_FOLLOW_COMPANY';
export const UN_FOLLOW_COMPANY_SUCCESS = 'UN_FOLLOW_COMPANY_SUCCESS';

export const OPEN_COMPANY_DIALOG = 'OPEN_COMPANY_DIALOG';
export const CLOSE_COMPANY_DIALOG = 'CLOSE_COMPANY_DIALOG';
