export const GET_LIST_CANDIDATES_FOR_EMPLOYER =
  'GET_LIST_CANDIDATES_FOR_EMPLOYER';
export const GET_LIST_CANDIDATES_FOR_EMPLOYER_SUCCESS =
  'GET_LIST_CANDIDATES_FOR_EMPLOYER_SUCCESS';

export const ADMIN_GET_CANDIDATES_LIST = ' ADMIN_GET_CANDIDATES_LIST';
export const ADMIN_GET_CANDIDATES_LIST_SUCCESS =
  ' ADMIN_GET_CANDIDATES_LIST_SUCCESS';
export const ADMIN_GET_CANDIDATES_LIST_FAILURE =
  ' ADMIN_GET_CANDIDATES_LIST_FAILURE';

// candidates status

export const OPEN_STATUS_DIALOG = 'OPEN_STATUS_DIALOG';
export const CLOSE_STATUS_DIALOG = 'CLOSE_STATUS_DIALOG';

export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE';

export const GET_DETAIL_CANDIDATE = 'GET_DETAIL_CANDIDATE';
export const GET_DETAIL_CANDIDATE_SUCCESS = 'GET_DETAIL_CANDIDATE_SUCCESS';
export const GET_DETAIL_CANDIDATE_FAILURE = 'GET_DETAIL_CANDIDATE_FAILURE';

export const SEARCH_CANDIDATES = 'SEARCH_CANDIDATES';
export const SEARCH_CANDIDATES_SUCCESS = 'SEARCH_CANDIDATES_SUCCESS';
export const SEARCH_CANDIDATES_FAILURE = 'SEARCH_CANDIDATES_FAILURE';

export const GET_DETAIL_RESUME_CANDIDATE = 'GET_DETAIL_RESUME_CANDIDATE';
export const GET_DETAIL_RESUME_CANDIDATE_SUCCESS =
  'GET_DETAIL_RESUME_CANDIDATE_SUCCESS';
export const GET_DETAIL_RESUME_CANDIDATE_FAILURE =
  'GET_DETAIL_RESUME_CANDIDATE_FAILURE';

//mails
export const OPEN_MAIL = 'OPEN_MAIL';
export const CLOSE_MAIL = 'CLOSE_MAIL';

export const SELECT_CANDIDATE = 'SELECT_CANDIDATE';

export const EMPLOYER_SEND_MAIL = 'EMPLOYER_SEND_MAIL';
export const EMPLOYER_SEND_MAIL_SUCCESS = 'EMPLOYER_SEND_MAIL_SUCCESS';
export const EMPLOYER_SEND_MAIL_FAILURE = 'EMPLOYER_SEND_MAIL_FAILURE';

export const EMPLOYER_GET_SENT_MAIL_LIST = 'EMPLOYER_GET_SENT_MAIL_LIST';
export const EMPLOYER_GET_SENT_MAIL_LIST_SUCCESS =
  'EMPLOYER_GET_SENT_MAIL_LIST_SUCCESS';
export const EMPLOYER_GET_SENT_MAIL_LIST_FAILURE =
  'EMPLOYER_GET_SENT_MAIL_LIST_FAILURE';

export const EMPLOYER_GET_CANDIDATES_BY_JOB = 'EMPLOYER_GET_CANDIDATES_BY_JOB';
export const EMPLOYER_GET_CANDIDATES_BY_JOB_SUCCESS =
  'EMPLOYER_GET_CANDIDATES_BY_JOB_SUCCESS';
export const EMPLOYER_GET_CANDIDATES_BY_JOB_FAILURE =
  'EMPLOYER_GET_CANDIDATES_BY_JOB_FAILURE';

// save
export const OPEN_SAVE = 'OPEN_SAVE';
export const CLOSE_SAVE = 'CLOSE_SAVE';

export const SAVE_CANDIDATE = 'SAVE_CANDIDATE';
export const SAVE_CANDIDATE_SUCCESS = 'SAVE_CANDIDATE_SUCCESS';
export const SAVE_CANDIDATE_FAILURE = 'SAVE_CANDIDATE_FAILURE';

export const GET_SAVED_CANDIDATES = 'GET_SAVED_CANDIDATES';
export const GET_SAVED_CANDIDATES_SUCCESS = 'GET_SAVED_CANDIDATES_SUCCESS';
export const GET_SAVED_CANDIDATES_FAILURE = 'GET_SAVED_CANDIDATES_FAILURE';

export const GET_SAVED_CANDIDATES_BY_FOLDER = 'GET_SAVED_CANDIDATES_BY_FOLDER';
export const GET_SAVED_CANDIDATES_BY_FOLDER_SUCCESS =
  'GET_SAVED_CANDIDATES_BY_FOLDER_SUCCESS';

export const DELETE_SAVED_CANDIDATE = 'DELETE_SAVED_CANDIDATE';
export const DELETE_SAVED_CANDIDATE_SUCCESS = 'DELETE_SAVED_CANDIDATE_SUCCESS';
export const DELETE_SAVED_CANDIDATE_FAILURE = 'DELETE_SAVED_CANDIDATE_FAILURE';

//Admin update status candidate
export const ADMIN_UPDATE_STATUS_CANDIDATE = 'ADMIN_UPDATE_STATUS_CANDIDATE';
export const ADMIN_UPDATE_STATUS_CANDIDATE_SUCCESS =
  'ADMIN_UPDATE_STATUS_CANDIDATE_SUCCESS';

export const IS_OPEN_DETAIL_ORDERS_DIALOG = 'IS_OPEN_DETAIL_ORDERS_DIALOG';
