export const GET_LIST_CANDIDATES_FOR_EMPLOYER =
  'GET_LIST_CANDIDATES_FOR_EMPLOYER';
export const GET_LIST_CANDIDATES_FOR_EMPLOYER_SUCCESS =
  'GET_LIST_CANDIDATES_FOR_EMPLOYER_SUCCESS';

export const ADMIN_GET_CANDIDATES_LIST = ' ADMIN_GET_CANDIDATES_LIST';
export const ADMIN_GET_CANDIDATES_LIST_SUCCESS =
  ' ADMIN_GET_CANDIDATES_LIST_SUCCESS';
export const ADMIN_GET_CANDIDATES_LIST_FAILURE =
  ' ADMIN_GET_CANDIDATES_LIST_FAILURE';
