export const GET_LIST_CANDIDATES_FOR_EMPLOYER =
  'GET_LIST_CANDIDATES_FOR_EMPLOYER';
export const GET_LIST_CANDIDATES_FOR_EMPLOYER_SUCCESS =
  'GET_LIST_CANDIDATES_FOR_EMPLOYER_SUCCESS';

export const ADMIN_GET_CANDIDATES_LIST = ' ADMIN_GET_CANDIDATES_LIST';
export const ADMIN_GET_CANDIDATES_LIST_SUCCESS =
  ' ADMIN_GET_CANDIDATES_LIST_SUCCESS';
export const ADMIN_GET_CANDIDATES_LIST_FAILURE =
  ' ADMIN_GET_CANDIDATES_LIST_FAILURE';

export const UPDATE_STATUS = 'UPDATE_STATUS';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAILURE = 'UPDATE_STATUS_FAILURE';

export const GET_DETAIL_CANDIDATE = 'GET_DETAIL_CANDIDATE';
export const GET_DETAIL_CANDIDATE_SUCCESS = 'GET_DETAIL_CANDIDATE_SUCCESS';
export const GET_DETAIL_CANDIDATE_FAILURE = 'GET_DETAIL_CANDIDATE_FAILURE';

export const SEARCH_CANDIDATES = 'SEARCH_CANDIDATES';
export const SEARCH_CANDIDATES_SUCCESS = 'SEARCH_CANDIDATES_SUCCESS';
export const SEARCH_CANDIDATES_FAILURE = 'SEARCH_CANDIDATES_FAILURE';

export const GET_DETAIL_RESUME_CANDIDATE = 'GET_DETAIL_RESUME_CANDIDATE';
export const GET_DETAIL_RESUME_CANDIDATE_SUCCESS =
  'GET_DETAIL_RESUME_CANDIDATE_SUCCESS';
export const GET_DETAIL_RESUME_CANDIDATE_FAILURE =
  'GET_DETAIL_RESUME_CANDIDATE_FAILURE';

export const SAVE_CANDIDATE = 'SAVE_CANDIDATE';
export const SAVE_CANDIDATE_SUCCESS = 'SAVE_CANDIDATE_SUCCESS';
export const SAVE_CANDIDATE_FAILURE = 'SAVE_CANDIDATE_FAILURE';

export const GET_SAVED_CANDIDATES = 'GET_SAVED_CANDIDATES';
export const GET_SAVED_CANDIDATES_SUCCESS = 'GET_SAVED_CANDIDATES_SUCCESS';
export const GET_SAVED_CANDIDATES_FAILURE = 'GET_SAVED_CANDIDATES_FAILURE';

export const DELETE_SAVED_CANDIDATE = 'DELETE_SAVED_CANDIDATE';
export const DELETE_SAVED_CANDIDATE_SUCCESS = 'DELETE_SAVED_CANDIDATE_SUCCESS';
export const DELETE_SAVED_CANDIDATE_FAILURE = 'DELETE_SAVED_CANDIDATE_FAILURE';
