export const GET_LIST_SERVICES_EMPLOYER = 'GET_LIST_SERVICES_EMPLOYER';
export const GET_LIST_SERVICES_EMPLOYER_SUCCESS =
  'GET_LIST_SERVICES_EMPLOYER_SUCCESS';
export const GET_LIST_SERVICES_EMPLOYER_FAILURE =
  'GET_LIST_SERVICES_EMPLOYER_FAILURE';

export const CREATE_SERVICE = 'CREATE_SERVICE';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_SUCCESS_FAILURE';

export const ADMIN_GET_SERVICES_LIST = 'ADMIN_GET_SERVICES_LIST';
export const ADMIN_GET_SERVICES_LIST_SUCCESS =
  'ADMIN_GET_LIST_SERVICES_SUCCESS';
export const ADMIN_GET_SERVICES_LIST_LIST_FAILURE =
  ' ADMIN_GET_LIST_SERVICES_FAILURE';

export const UPDATE_SERVICE = ' UPDATE_SERVICE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAILURE = 'UPDATE_SERVICE_FAILURE';

export const DELETE_SERVICE = 'DELETE_SERVICE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_ITEM = 'DELETE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const INCREASE_ITEM = 'INCREASE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const EMPLOYER_ORDER_SERVICES = 'EMPLOYER_ORDER_SERVICES';
export const EMPLOYER_ORDER_SERVICES_SUCCESS =
  'EMPLOYER_ORDER_SERVICES_SUCCESS';
export const EMPLOYER_ORDER_SERVICES_FAILURE =
  'EMPLOYER_ORDER_SERVICES_FAILURE';

export const EMPLOYER_GET_ORDERED_SERVICES = 'EMPLOYER_GET_ORDERED_SERVICES';
export const EMPLOYER_GET_ORDERED_SERVICES_SUCCESS =
  'EMPLOYER_GET_ORDERED_SERVICES_SUCCESS';
export const EMPLOYER_GET_ORDERED_SERVICES_FAILURE =
  'EMPLOYER_GET_ORDERED_SERVICES_FAILURE';

export const EMPLOYER_GET_DETAIL_ORDERED_SERVICE =
  'EMPLOYER_GET_DETAIL_ORDERED_SERVICE';
export const EMPLOYER_GET_DETAIL_ORDERED_SERVICE_SUCCESS =
  'EMPLOYER_GET_DETAIL_ORDERED_SERVICE_SUCCESS';
export const EMPLOYER_GET_DETAIL_ORDERED_SERVICE_FAILURE =
  'EMPLOYER_GET_DETAIL_ORDERED_SERVICE_FAILURE';

export const ADMIN_GET_ORDERED_SERVICES = 'ADMIN_GET_ORDERED_SERVICES';
export const ADMIN_GET_ORDERED_SERVICES_SUCCESS =
  'ADMIN_GET_ORDERED_SERVICES_SUCCESS';
export const ADMIN_GET_ORDERED_SERVICES_FAILURE =
  'ADMIN_GET_ORDERED_SERVICES_FAILURE';

export const ADMIN_UPDATE_STATUS_ORDERED_SERVICES =
  'ADMIN_UPDATE_STATUS_ORDERED_SERVICES';
export const ADMIN_UPDATE_STATUS_ORDERED_SERVICES_SUCCESS =
  'ADMIN_UPDATE_STATUS_ORDERED_SERVICES_SUCCESS';
export const ADMIN_UPDATE_STATUS_ORDERED_SERVICES_FAILURE =
  'ADMIN_UPDATE_STATUS_ORDERED_SERVICES_FAILURE';

export const EMPLOYER_GET_ACTIVE_SERVICES = 'EMPLOYER_GET_ACTIVE_SERVICES';
