export const GET_LIST_SERVICES_EMPLOYER = 'GET_LIST_SERVICES_EMPLOYER';
export const GET_LIST_SERVICES_EMPLOYER_SUCCESS =
  'GET_LIST_SERVICES_EMPLOYER_SUCCESS';
export const GET_LIST_SERVICES_EMPLOYER_FAILURE =
  'GET_LIST_SERVICES_EMPLOYER_FAILURE';

export const CREATE_SERVICE = 'CREATE_SERVICE';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_SUCCESS_FAILURE';

export const UPDATE_SERVICE = ' UPDATE_SERVICE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAILURE = 'UPDATE_SERVICE__FAILURE';

export const DELETE_SERVICE = 'DELETE_SERVICE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';

export const ADMIN_GET_SERVICES_LIST = 'ADMIN_GET_SERVICES_LIST';
export const ADMIN_GET_LIST_SERVICES_SUCCESS =
  'ADMIN_GET_LIST_SERVICES_SUCCESS';
export const ADMIN_GET_LIST_SERVICES_LIST_FAILURE =
  ' ADMIN_GET_LIST_SERVICES_FAILURE';
