export const GET_LIST_SERVICES_EMPLOYER = 'GET_LIST_SERVICES_EMPLOYER';
export const GET_LIST_SERVICES_EMPLOYER_SUCCESS =
  'GET_LIST_SERVICES_EMPLOYER_SUCCESS';
export const GET_LIST_SERVICES_EMPLOYER_FAILURE =
  'GET_LIST_SERVICES_EMPLOYER_FAILURE';
